### ISSUE TITLE
DockerFiles of OntoWiki are misssing

### ISSUE THREAD

**Issue by landkommunenhippie** [heloisenetwork/infrastructure#1]
# Missing Build-Files

There is neither a Dockerfile nor configfiles for ontowiki. 
They have to be added to docker/ontowiki which is empty atm. 

@triechert  I commented out entry to build ontowiki.

**Comment by landkommunenhippie** [comment]
I am not able to push to the repo

**Comment by triechert** [comment]
I added ontowiki.
